# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ['AlexTemp']
  pull_request:
    branches: ['AlexTemp']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Publish
        run: dotnet publish CookWithWhat.API/CookWithWhat.API.csproj --configuration Release --runtime linux-x64 --self-contained --output ./out
      - name: Copy to the EC2 instance
        uses: appleboy/scp-action@master
        env:
          HOST: '18.168.152.55'
          USERNAME: ec2-user
          KEY: ${{ secrets.SSH_KEY }}
        with:
          source: './CookWithWhat.API/out/*'
          target: '/home/ec2-user/app '

        # run:  scp -i CWW.pem -r ./CookWithWhat.API/out/* ec2-user@18.168.152.55:/home/ec2-user/app
